#!/usr/bin/python
#      timeball : the main run file of the application
#      Copyright (C) 2013  Kevin Brandstatter <icarusthecow@gmail.com>
#
#      This program is free software; you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation; either version 2 of the License, or
#      (at your option) any later version.


from sys import argv
from timeball_utils import argparser
from timeball_utils.configparser import config_parser
from timeball_utils.version import version
import os
print "timeball version " + version
import logging
from timeball_utils.argparser import log_levels
logging.basicConfig(format="%(asctime)s - %(levelname)s: %(message)s")

opts = argparser.parse_cl()
#print opts
#import sys
#sys.exit(1)
logging.getLogger().setLevel(log_levels[opts['log_level'].lower()])

if argv[1] is None:
   print "No option given"
elif argv[1] == "backup":
   from timeball_utils import backup
   cparse = config_parser(os.environ['HOME'] + "/.timeball")
   copts = cparse.get_options(profile=opts['profile'])
   opts = argparser.parse_cl(options=copts)
   backup.run(opts)
elif argv[1] == "recover":
   from timeball_utils import recover
   recover.run(opts)
   #recover.run(argv[1:])
elif argv[1] == "delete":
   from timeball_utils import delete
   delete.run(opts)
else:
   print "Invalid operation"

