#!/usr/bin/python
#      timeball : the main run file of the application
#      Copyright (C) 2013  Kevin Brandstatter <icarusthecow@gmail.com>
#
#      This program is free software; you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation; either version 2 of the License, or
#      (at your option) any later version.


from sys import argv
from timeball_utils import argparser
from timeball_utils.configparser import config_parser
from timeball_utils.version import version
import os
print "timeball version " + version
import logging
from timeball_utils.argparser import log_levels, get_options
from sys import argv
logging.basicConfig(format="%(asctime)s - %(levelname)s: %(message)s")

argv.pop(0) # pop the program name
#print opts
import sys
#sys.exit(1)
#logging.getLogger().setLevel(log_levels[opts['log_level'].lower()])
opts = get_options()
print opts
sys.exit(0)


if opts['back_type'] is None:
   print "No option given"
elif opts['back_type'] == "backup":
   from timeball_utils import backup
   backup.run(opts)
elif opts['back_type'] == "recover":
   from timeball_utils import recover
   recover.run(opts)
elif opts['back_type'] == "delete":
   from timeball_utils import delete
   delete.run(opts)
else:
   print "Invalid operation"

