#!/usr/bin/python
#      timeball : the main run file of the application
#      Copyright (C) 2013  Kevin Brandstatter <icarusthecow@gmail.com>
#
#      This program is free software; you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation; either version 2 of the License, or
#      (at your option) any later version.


from sys import argv
from timeball_utils import backup, recover, delete
from timeball_utils.configparser import usage
from timeball_utils.version import version
print "timeball version @VERSION@"

if argv[1] is None:
   print "No option given"
elif argv[1] == "backup":
   backup.run(argv[1:])
elif argv[1] == "recover":
   recover.run(argv[1:])
elif argv[1] == "delete":
   delete.run(argv[1:])
elif argv[1] == "--help":
   print usage
else:
   print "Invalid operation"

